name: 'SPDX-to-dependency-graph-action'
description: 'Upload SPDX files to the dependency graph'
inputs:
  filePath:  
    description: 'The path to the directory containing the SPDX files to upload. Defaults to Actions working directory.'
    required: false
    default: '.'
  filePattern:
    description: 'The file name pattern for SPDX files to upload'
    required: false
    default: '*.spdx.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
