name: "Test"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        filePath: "test"
        
